### ISSUE TITLE
Multi-tenancy - you can only install a single tenant

### ISSUE THREAD

**Issue by izi** [fhirbase/fhirbase-plv8#75]
In latest beta the:

```
CREATE AGGREGATE public.FIRST...
```

Does not work when installing other tenant into a different schema. Works only for the first tenant.

**Comment by niquola** [comment]
Should work? It seems not fhirbase scope ;) just adjust schema path.

**Comment by izi** [comment]
The search path works. The issue is that the CREATE AGGREGATE is created in public schema explicitly.

When run multiple times for different tenants you will see:

```
...
CREATE FUNCTION
psql:schema/fhirbase-0.0.1-beta.5.sql:43: ERROR:  function "first" already exists with same argument types
...
```

Our tooling will rollback any changes if anything fails.

**Comment by niquola** [comment]
Again, this problem is between  you and postgresql, nothing related to fhirbase. Do not create any functions in public schema, put them in  tenant schemas. When you decided to go with tenants in schemas, you had to be prepared to such types of problems. We use db per tenant for isolation by the cost of connection.

**Comment by niquola** [comment]
Fix fb migration

**Comment by danil** [comment]
@izi please try v0.0.1-beta.6 (tested on two schemas https://github.com/fhirbase/fhirbase-plv8/blob/v0.0.1-beta.6/.travis.yml#L26)

**Comment by izi** [comment]
It works fine. Thanks.
